from __future__ import annotations

from enum import Enum


class RunnerFailureReason(str, Enum):
    NONCANONICAL_ENCODING = "NONCANONICAL_ENCODING"
    HASH_ORIGIN_MISMATCH = "HASH_ORIGIN_MISMATCH"
    LOGICAL_DEPENDENCY_GATE_VIOLATION = "LOGICAL_DEPENDENCY_GATE_VIOLATION"
    SCHEMA_VIOLATION = "SCHEMA_VIOLATION"
    COVERAGE_STRUCTURE_VIOLATION = "COVERAGE_STRUCTURE_VIOLATION"
    SHARED_ENDPOINT_BYTES_MISMATCH = "SHARED_ENDPOINT_BYTES_MISMATCH"
    KERNEL_IDENTITY_MISMATCH = "KERNEL_IDENTITY_MISMATCH"
    REQUIRED_STORED_RECORD_MISSING = "REQUIRED_STORED_RECORD_MISSING"
    INTERNAL_INCONSISTENCY = "INTERNAL_INCONSISTENCY"
    ANCHOR_PREDICATE_VIOLATION = "ANCHOR_PREDICATE_VIOLATION"
    SNAPSHOT_MISMATCH = "SNAPSHOT_MISMATCH"
    PILOT_IDENTITY_MISMATCH = "PILOT_IDENTITY_MISMATCH"
    DESIGN_IDENTITY_MISMATCH = "DESIGN_IDENTITY_MISMATCH"
    STRICT_SIGN_FAIL = "STRICT_SIGN_FAIL"
    NONFINITE_ENCLOSURE = "NONFINITE_ENCLOSURE"
    WINDOW_GENERATION_FAIL = "WINDOW_GENERATION_FAIL"
    WINDOW_OVERLAP_IMPOSSIBLE = "WINDOW_OVERLAP_IMPOSSIBLE"
    INHERITED_OVERLAP_INSUFFICIENT = "INHERITED_OVERLAP_INSUFFICIENT"
    ICG_NOT_CONTAINED = "ICG_NOT_CONTAINED"
    R_CELL_BUDGET_EXCEEDED = "R_CELL_BUDGET_EXCEEDED"
    PER_BOX_EVAL_LIMIT_REACHED = "PER_BOX_EVAL_LIMIT_REACHED"
    GLOBAL_EVAL_LIMIT_REACHED = "GLOBAL_EVAL_LIMIT_REACHED"


class CheckerFailureReason(str, Enum):
    """Checker/verifier-only closed enum.

    These values are intentionally outside RunnerFailureReason.  They describe
    rejection of an artifact, not a mathematical or runner-local failure.
    """

    NONCANONICAL_ARTIFACT = "NONCANONICAL_ARTIFACT"
    CONFIG_SCHEMA_VIOLATION = "CONFIG_SCHEMA_VIOLATION"
    LOGICAL_DEPENDENCY_VIOLATION = "LOGICAL_DEPENDENCY_VIOLATION"
    FAILURE_TRANSITION_VIOLATION = "FAILURE_TRANSITION_VIOLATION"
    RECORD_GRAMMAR_VIOLATION = "RECORD_GRAMMAR_VIOLATION"
    FRONTIER_REDERIVATION_MISMATCH = "FRONTIER_REDERIVATION_MISMATCH"
    WINDOW_REDERIVATION_MISMATCH = "WINDOW_REDERIVATION_MISMATCH"
    PREDICTOR_CONTEXT_MISMATCH = "PREDICTOR_CONTEXT_MISMATCH"
    COVERAGE_MANIFEST_VIOLATION = "COVERAGE_MANIFEST_VIOLATION"
    FRESH_EVALUATION_FAIL = "FRESH_EVALUATION_FAIL"
    SOURCE_IDENTITY_FAIL = "SOURCE_IDENTITY_FAIL"
    PILOT_IDENTITY_FAIL = "PILOT_IDENTITY_FAIL"
    CHAIN_VIOLATION = "CHAIN_VIOLATION"
    CERTIFICATION_WORD_VIOLATION = "CERTIFICATION_WORD_VIOLATION"
    CONTROL_MAPPING_VIOLATION = "CONTROL_MAPPING_VIOLATION"


class RunnerTerminalClass(str, Enum):
    NORMAL_COMPLETE = "NORMAL_COMPLETE"
    NORMAL_INCOMPLETE = "NORMAL_INCOMPLETE"
    RUN_FATAL = "RUN_FATAL"


class CheckerTerminalClass(str, Enum):
    VERIFY_PASS = "VERIFY_PASS"
    VERIFY_FAIL = "VERIFY_FAIL"


class AttemptStage(str, Enum):
    PRIMARY = "PRIMARY"
    REGENERATED = "REGENERATED"


class WindowOrigin(str, Enum):
    CONFIG_SEED = "CONFIG_SEED"
    PARENT_INHERITED = "PARENT_INHERITED"
    PREDICTOR_HORIZONTAL = "PREDICTOR_HORIZONTAL"
    PREDICTOR_LINEAR = "PREDICTOR_LINEAR"


class PrimaryWindowMode(str, Enum):
    PARENT_INHERITED = "PARENT_INHERITED"
    PREDICTOR_AT_ACTIVATION = "PREDICTOR_AT_ACTIVATION"


class RecordType(str, Enum):
    BOX_ATTEMPT_FAIL = "BOX_ATTEMPT_FAIL"
    SLICE_BOX_PASS = "SLICE_BOX_PASS"
    SLICE_BOX_FAIL = "SLICE_BOX_FAIL"
    SPLIT = "SPLIT"
    FRONTIER_STOP = "FRONTIER_STOP"
    RUN_FATAL = "RUN_FATAL"
    SWEEP_COMPLETE = "SWEEP_COMPLETE"
    SWEEP_INCOMPLETE = "SWEEP_INCOMPLETE"
    VERIFIED_BOX_PASS = "VERIFIED_BOX_PASS"
    VERIFY_PASS = "VERIFY_PASS"
    VERIFY_FAIL = "VERIFY_FAIL"
